### ISSUE TITLE
5.17 upgrade checklist

### ISSUE THREAD

**Issue by benesch** [cockroachdb/rocksdb#22]
- [ ] **b4db6b43a Remove unused variables that the compiler is complaining about**
- [x] **45fbaf2f9 Pass manual_wal_flush also to the first wal file**
   Original upstream commit 718c1c9c1f01ce4a3c0f4ae488e78f583d40a38c is present.
- [x] **fb75bc2c3 Rename function for handling WAL write error**
   Original upstream commit 4d51feab0bc0d0a209a0606afa6b2857737bb0f5 is present.
- [x] **a66ad5a0e check return status for Sync() and Append() calls to avoid corruption**
   Original upstream commit e1e826b9805e6412b8f91ef376657f4911e49f72 is present.
- [x] **[peter] ff5ecc374 Fix range tombstones written to more files than necessary (#4592)**
  Backported as 27ad7fe6d42eadf8772e16f4bcd628679be5ff77.
- [x] **a79dcf410 add kEntryRangeDeletion**
   Original upstream commit 31ee4bf2400cf1807718192d352ca8bd7837ada2 is present.
- [x] **[peter] 99a3aebf2 Fix merge operand reappearing when covered by DeleteRange (#4481)**
  Backported as 13de2e56dc8341f861919dea6f1fdeef0814b971.
- [x] **[peter] 6a78d8a97 DeleteRange regression tests using public API (#4476)**
  Backported as 88208f18b6f772cdce981e02070895f0db1381e6.
- [x] **[peter] 6f1195922 Extend PartialRangeTombstone to use InternalKeys**
  Forward ported as 1e342df9063e9ef01e08492fa998bcf98ea2b19c.
- [x] **[peter] a8370d4a6 Truncate range tombstones by leveraging InternalKeys (#4432)**
  Backported as f9dbc8a6bcd665b9e02660107d38ba9234ff0e5a.
- [x] **5bd0dca7f Fix a lint error due to unspecified move evaluation order (#4348)**
   Original upstream commit ced618cf393e4e80bf78dfc60a2dafefeb898ff1 is present.
- [x] **[peter] 7a67fd5da Support non-pinned keys/vals in RangeDelAggregator**
  Original upstream commit ef7815b803fe8a264466b92f20f04e03f1f45972 is present.
- [x] **d0104d92d Add some missing override keywords**
   Unnecessary.
- [x] **0721e1b75 Add SST ingestion to ldb (#4205)**
   Original upstream commit de7f423a82363b667e5bf5c714277135d2f79f39 is present.
- [x] **db4581333 Unit test for custom comparator RangeDelAggregator (#4388)**
   Original upstream commit 990b52e95b3b2d7bac72ef468a3f5665497145c3 is present.
- [x] **372d4cedc Skip range deletions at seqno zero when collapsing (#4216)**
   Original upstream commit f8f6983f8978969802d56c231b5af7b5c427488b is present.
- [x] **1cbf8b0a7 Reorder CollapsedRangeDelMap conditional to match upstream**
   Unnecessary.
- [x] **5d12dc2cb Reformat range_del_aggregator.cc to match upstream style**
   Unnecessary.
- [x] **625f02c32 Handle tombstones at the same seqno in the CollapsedRangeDelMap**
   Original upstream commit 17edc82a4ba3d4455b9fe86632f11e47df4a16e1 is present.
- [x] **[peter] d62a9980e Fix a bug in iteration while skipping range deletion tombstones**
  Forward ported as c96799185ae6dd09f94714818f82203cda39af5c.
- [x] **[peter] baf0248e6 Restrict RangeDelAggregator's tombstone end-key truncation**
  Original upstream commit c86a22ac433efb87a7c73449d7aa5ef6c4580530 is present.
- [x] **[peter] 55ffa77e4 Adjust wording of PartialRangeTombstone description**
  Forward ported as 13c8e70f4e533f2d3e481faa46c48a1d78c91ae3.
- [x] **[peter] 12db3d2ca Fix memory bug in CollapsedRangeDelMap::GetTombstone**
  Forward ported as 43bec7e398ce9cdab6a1bf3c5fbf25c1d58087e1.
- [x] **[peter] 6b64b6f1c Fix skipping of range deleted keys in BlockBasedTableIterator**
  Forward ported as ac96261ad1931c24ec94c176585d0a0c56d3b72e.
- [x] **1f026609c Fix GitHub issue #3716: gcc-8 warnings**
   Original upstream commit dee95a1afc6c63515e7d94dec33acdb79638b6d7 is present.
- [x] **[peter] 2a2715993 Properly handle range tombstones at the same seqnum as a key**
  Forward ported as d793039c91dfb48263d120b46c66f99ec362f1b4.
- [x] **[peter] e2be260b6 Stop-gap for unimplemented UncollapsedRangeDelMap::ShouldDeleteRange**
  Forward ported as eb50d7493e0c634df8767ff46a30db61cae00e0c.
- [x] **d6b024760 Relax VersionStorageInfo::GetOverlappingInputs check**
   Original upstream commit 90fc40690a9184111295d4c8e1cc1ba4c25e2f87 is present.
- [x] **[peter] ce6b81d4f Truncate range tombstones from sstables**
   Original upstream commit 90fc40690a9184111295d4c8e1cc1ba4c25e2f87 is present.
- [x] **[peter] 450e91aaf Removed the unused TableCache::NewRangeTombstoneIterator**
   Original upstream commit 90fc40690a9184111295d4c8e1cc1ba4c25e2f87 is present.
- [x] **[peter] 1eeec9afc Skip ranges of deleted keys in BlockBasedTableIterator**
  Forward ported as e80b4e3ea4895a12a9cce5debc94ba45f6fe5a6a.
- [x] **[peter] c147ea0b8 Add RangeDelAggregator::GetTombstone**
  Forward ported as 2b588fe3a8bd805a55cff89ab3a1bd8ddeece60f.
- [x] **[peter] e4db21863 Skip L0 sstables which are covered by a range tombstone**
  Forward ported as 281795216f315111f3f222060ff219bc66bfcf92.
- [x] **[peter] 9460832de Skip sstables that are entirely covered by a range tombstone**
  Forward ported as d88fd4bb0214622401ba191c13490c2bc6536519.
- [x] **92b9e8432 Range deletion performance improvements + cleanup (#4014)**
   Original upstream commit 5f3088d5656c483348c9aa32b048a1f8d4920eee is present.
- [x] **de886989a Add table property tracking number of range deletions (#4016)**
   Original upstream commit 17339dc2f39a87a9cf097e056a59560b0795ff6e is present.
- [x] **875840980 Recommit "Avoid adding tombstones of the same file to RangeDelAggregator multiple times"**
   Original upstream commit 72942ad7a40d23ef9b6edf6cf1f53628e37c56b4 is present.
- [x] **edd4b23e0 Test range deletions with more configurations**
   Original upstream commit 5cd8240b86fd0f0ed07ad4d6ac7cff3130a77ca6 is present.
- [x] **8865dc6f6 Fix race condition via concurrent FlushWAL**
   Original upstream commit 35a4469bbfa9a5360d600d4c3c1a5a87178ac171 is present.
- [x] **7ca2e5b1f Check conflict at output level in CompactFiles**
   Original upstream commit 4420df4b0e15ae88911e960c4fbafbaf8450fcf7 is present.
- [x] **c3a10db24 util/crc32c: always compile FastCRC32 with SSE4.2 instructions**
   Forward ported as af810f1acc16ae15f09b72aa4ee512fcabf341fe.

**Comment by petermattis** [comment]
Current status is running into problems forward porting 1eeec9afc315994d55e7dd16436e259af605b585. Patches have been tweaked, but there are test failures. Will continue tomorrow or Friday.
