### ISSUE TITLE
6.2 upgrade checklist

### ISSUE THREAD

**Issue by ajkr** [cockroachdb/rocksdb#37]
checklist generation command:
```
git log --no-decorate v5.17.2..origin/crl-release-5.17.2 --pretty=oneline | tac | awk '{print "- [ ] **" $0 "**"}'
```

branch: https://github.com/cockroachdb/rocksdb/tree/crl-release-6.2.1

checklist:
- [x] **feeaa41120ef713d4529d42d06e6d599beb4044b Fix jemalloc mangling** Backported commit a372449b362835706e1a699db3923ae372bc5992 for unlanded upstream PR (https://github.com/facebook/rocksdb/pull/5521)
- [x] **af810f1acc16ae15f09b72aa4ee512fcabf341fe util/crc32c: always compile FastCRC32 with SSE4.2 instructions** Backported commit cd5bfb691cc01577277ac59c88e438e705e7e0b3 for unlanded upstream PR (https://github.com/facebook/rocksdb/pull/5511)
- [x] **f9dbc8a6bcd665b9e02660107d38ba9234ff0e5a Truncate range tombstones by leveraging InternalKeys (#4432)** Original upstream commit f9dbc8a6bcd665b9e02660107d38ba9234ff0e5a is present
- [x] **5db10838574f8a16613841ea740b656998c7db96 Fix printf compiler warning** Original upstream commit f959e88048642f3548065d07306ad7a0ffdeaa7e is present
- [x] **88208f18b6f772cdce981e02070895f0db1381e6 DeleteRange regression tests using public API (#4476)** Original upstream commit faa70fc575b6498ccd334a59780eaabc4f496762 is present
- [x] **13de2e56dc8341f861919dea6f1fdeef0814b971 Fix merge operand reappearing when covered by DeleteRange (#4481)** Original upstream commit 7e56072290269302cad535d3d67177ed9f6e939d is present
- [x] **27ad7fe6d42eadf8772e16f4bcd628679be5ff77 Fix range tombstones written to more files than necessary (#4592)** Original upstream commit cae540ebefe57c5c2e56b650574511dbfcc20efb is present
- [x] **d88fd4bb0214622401ba191c13490c2bc6536519 Skip sstables that are entirely covered by a range tombstone** Dropped (time constraints).
- [x] **eb50d7493e0c634df8767ff46a30db61cae00e0c Stop-gap for unimplemented UncollapsedRangeDelMap::ShouldDeleteRange** Dropped (time constraints).
- [x] **281795216f315111f3f222060ff219bc66bfcf92 Skip L0 sstables which are covered by a range tombstone** Dropped (time constraints).
- [ ] **2b588fe3a8bd805a55cff89ab3a1bd8ddeece60f Add RangeDelAggregator::GetTombstone** Non-blocking. Upstream PR is: https://github.com/facebook/rocksdb/pull/5506
- [ ] **d793039c91dfb48263d120b46c66f99ec362f1b4 Properly handle range tombstones at the same seqnum as a key** Non-blocking. Upstream PR is: https://github.com/facebook/rocksdb/pull/5506
- [x] **c0f547ba9ed2892429803c4ea2e52dea16441af7 Fix RepeatableThreadTest::MockEnvTest hang (#4560)** Original upstream commit 933250e355180d2d2c7815f79a186584e1963427 is present
- [ ] **e80b4e3ea4895a12a9cce5debc94ba45f6fe5a6a Skip ranges of deleted keys in BlockBasedTableIterator** Non-blocking. Upstream PR is: https://github.com/facebook/rocksdb/pull/5506
- [ ] **ac96261ad1931c24ec94c176585d0a0c56d3b72e Fix skipping of range deleted keys in BlockBasedTableIterator** Non-blocking. Upstream PR is: https://github.com/facebook/rocksdb/pull/5506
- [ ] **43bec7e398ce9cdab6a1bf3c5fbf25c1d58087e1 Fix memory bug in CollapsedRangeDelMap::GetTombstone** Non-blocking. Upstream PR is: https://github.com/facebook/rocksdb/pull/5506
- [ ] **13c8e70f4e533f2d3e481faa46c48a1d78c91ae3 Adjust wording of PartialRangeTombstone description** Non-blocking. Upstream PR is: https://github.com/facebook/rocksdb/pull/5506
- [ ] **c96799185ae6dd09f94714818f82203cda39af5c Fix a bug in iteration while skipping range deletion tombstones** Non-blocking. Upstream PR is: https://github.com/facebook/rocksdb/pull/5506
- [ ] **1e342df9063e9ef01e08492fa998bcf98ea2b19c Extend PartialRangeTombstone to use InternalKeys** Non-blocking. Upstream PR is: https://github.com/facebook/rocksdb/pull/5506
- [x] **dc306254a55939066488f15b9b48fb50c3ae6b63 Merge pull request #24 from petermattis/pmattis/range-delete** Dropped (no content).
- [x] **7bb890cf8d421a09cd35207295bbd3bd0d597d2e Allow file-ingest-triggered flush to skip waiting for write-stall clear (#4751)** Original upstream commit 9be3e6b48884c80733fa791b982a02f62a199e92 is present
- [x] **c905cbca7b5ac1ef59046cfa58e146458f499eec Merge pull request #25 from petermattis/pmattis/ingest-externa-file-deadlock** Dropped (no content)
- [x] **b238986bba8cc0d7c14e7b18956f2ddcd010e082 Use `fallocate` even if hole-punching unsupported** Original upstream commit 186b3afaa850053f2368ddc78eef4bdec59b85c0 is present
- [x] **47e4f25d7b30c5cdf077e4f96b945a2c6b790d7b Fix user comparator receiving internal key (#4575)** Original upstream commit c34cc4042420929410f1644bc1362d38e10b5eec is present
- [x] **67cd77a3b65521f0eeab015a3efa4caba6f3c1de ldb: set `total_order_seek` for scans** Original upstream commit 5a5c0492dbe0c478c3ce5ef34b0dc73b42b91ab4 is present
- [x] **3a50e3185bf8898a67155ec7bfa71fd05d0caff7 Fix #3840: only `SyncClosedLogs` for multiple CFs (#4460)** Original upstream commit a47868226087aebd87bc9d35104c7384c6cc7b00 is present
- [x] **2597e93f41bac8dcc90ea75aa9a853779aa1b2da Optionally wait on bytes_per_sync to smooth I/O** Original upstream commit 8272a6de57ed701fb25bb660e074cab703ed3fe7 is present
- [x] **0b91537f863b0ba5b704bbdd51f2a2f634ceeea1 Option string/map/file can set env from object registry (#5237)** Original upstream commit 6eb317bb4ce72d5809d07b4d33be550f75db113c is present
- [x] **c6d2b4a5aef18657ca3f88eb6c84db75bdfbe7fb Fix merging range tombstone covering put during flush/compaction (#5406)** Original upstream commit a1f08cc953954ff42077fc3fc4a845d54b7f6d38 is present
- [x] **c20082b75b97f02d597cbaad996fb9bc12e5b45a Potential fix for stress test failure due to "SST file ahead of WAL" error (#5412)** Backported upstream commit 45e9fec5217e49a9f79f92c32dfe43eabcff5aea is present
- [x] **62d3cdcd53e5beeb3ea12722123bd221e002079c Dynamic test whether sync_file_range returns ENOSYS** Backported upstream commit e9983306c5219040986cfb80b8912f91bb06cebe is present
- [x] **12db615788ee4876e8725b67898ac3e86d51bc72 Avoid deadlock between mutex_ and log_write_mutex_ (#5437)** Backported upstream commit ea2373f1f845c4c66b786b2cf5166cebe8007671 is present

**Comment by ajkr** [comment]
I marked the optimization to skip over sstables that are fully covered by range tombstones as dropped due to time constraints. I wasn't able to come up with a clean implementation of `ShouldDeleteRange` in the new `RangeDelAggregator` implementation (it is removed in the upstream PR). We can revisit it later with more time and ideas.

**Comment by petermattis** [comment]
> I marked the optimization to skip over sstables that are fully covered by range tombstones as dropped due to time constraints. I wasn't able to come up with a clean implementation of ShouldDeleteRange in the new RangeDelAggregator implementation (it is removed in the upstream PR). We can revisit it later with more time and ideas.

Ack. Ok.

**Comment by ajkr** [comment]
I was able to compile on Mac without feeaa41120ef713d4529d42d06e6d599beb4044b. Not sure what to do with it - maybe try dropping it and see if anyone else's build breaks? It is hard to submit upstream right now since I can't say what it fixes.

**Comment by benesch** [comment]
Were you able to link the Cockroach binary without that patch, or just
build RocksDB? If I recall correctly things don’t go wrong until you try to
link Cockroach.

**Comment by ajkr** [comment]
Thanks Nikhil :). It did appear to successfully link the cockroach binary. I could have made a mistake or could have been using different dependency versions (I was running on qemu on Linux as I don't have a real Mac). Let me try soliciting someone who actually uses Mac to help test.

**Comment by benesch** [comment]
Ah, gotcha. So if, using the current master, I run `cd c-deps/rocksdb && git revert feeaa41120ef && cd ../.. && make build`, I do see an error like:

```
/Users/benesch/go/src/github.com/cockroachdb/cockroach/c-deps/rocksdb/db/malloc_stats.cc:53:3: error: use
      of undeclared identifier 'malloc_stats_print'; did you mean 'je_malloc_stats_print'?
  malloc_stats_print(GetJemallocStatus, &mstat, "");
  ^~~~~~~~~~~~~~~~~~
  je_malloc_stats_print
/Users/benesch/go/native/x86_64-apple-darwin18.6.0/jemalloc/include/jemalloc/jemalloc.h:235:39: note: 
      'je_malloc_stats_print' declared here
JEMALLOC_EXPORT void JEMALLOC_NOTHROW   je_malloc_stats_print(
                                        ^
/Users/benesch/go/native/x86_64-apple-darwin18.6.0/jemalloc/include/jemalloc/jemalloc.h:77:33: note: 
      expanded from macro 'je_malloc_stats_print'
#  define je_malloc_stats_print je_malloc_stats_print
                                ^
1 error generated.
make[4]: *** [CMakeFiles/rocksdb.dir/db/malloc_stats.cc.o] Error 1
make[3]: *** [CMakeFiles/rocksdb.dir/all] Error 2
make[2]: *** [CMakeFiles/rocksdb.dir/rule] Error 2
make[1]: *** [rocksdb] Error 2
make: *** [/Users/benesch/go/native/x86_64-apple-darwin18.6.0/rocksdb/librocksdb.a] Error 2
```

But perhaps that's been fixed somehow in RocksDB 6.2!

**Comment by ajkr** [comment]
I see. Thanks for the build output. The candidate 6.2 release branch is here if you want to try: https://github.com/cockroachdb/rocksdb/tree/crl-release-6.2.1

**Comment by benesch** [comment]
I did try! But it looks like some changes are needed in lib roach, too? Is
there a corresponding patch for cockroachdb/cockroach that you've got handy?

**Comment by ajkr** [comment]
Oh really? Do you mind sharing the compiler error? I am building cockroach master branch against that rocksdb 6.2 branch and it seems to work.

**Comment by ajkr** [comment]
Never mind. TIL `make clean` followed by `make` resets the submodules. https://github.com/cockroachdb/cockroach/pull/38528

**Comment by benesch** [comment]
> Never mind. TIL make clean followed by make resets the submodules.

D'oh. Perhaps the rule for deleting `bin/.submodules-initialized` should be moved to `make unsafe-clean` to prevent the pitfall.

So your patch fixes the libroach compilation failure—thanks! I tested building the latest master with RocksDB pointed at crl-release-6.2.1 and got a jemalloc related error:

```
  "_dallocx", referenced from:
      rocksdb::DumpMallocStats(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*) in librocksdb.a(malloc_stats.cc.o)
  "_mallctl", referenced from:
      rocksdb::DumpMallocStats(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*) in librocksdb.a(malloc_stats.cc.o)
  "_mallctlbymib", referenced from:
      rocksdb::DumpMallocStats(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*) in librocksdb.a(malloc_stats.cc.o)
  "_mallctlnametomib", referenced from:
      rocksdb::DumpMallocStats(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*) in librocksdb.a(malloc_stats.cc.o)
  "_malloc_stats_print", referenced from:
      rocksdb::DumpMallocStats(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*) in librocksdb.a(malloc_stats.cc.o)
  "_malloc_usable_size", referenced from:
      rocksdb::DumpMallocStats(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*) in librocksdb.a(malloc_stats.cc.o)
  "_mallocx", referenced from:
      rocksdb::DumpMallocStats(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*) in librocksdb.a(malloc_stats.cc.o)
  "_nallocx", referenced from:
      rocksdb::DumpMallocStats(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*) in librocksdb.a(malloc_stats.cc.o)
  "_rallocx", referenced from:
      rocksdb::DumpMallocStats(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*) in librocksdb.a(malloc_stats.cc.o)
  "_sallocx", referenced from:
      rocksdb::DumpMallocStats(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*) in librocksdb.a(malloc_stats.cc.o)
  "_sdallocx", referenced from:
      rocksdb::DumpMallocStats(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*) in librocksdb.a(malloc_stats.cc.o)
  "_xallocx", referenced from:
      rocksdb::DumpMallocStats(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*) in librocksdb.a(malloc_stats.cc.o)
```

That error is indeed resolved by adding feeaa41 to the RocksDB submodule, albeit a bit modified for some upstream changes:

```diff
diff --git a/db/malloc_stats.cc b/db/malloc_stats.cc
index bcee5c3fb..1dfe0d55b 100644
--- a/db/malloc_stats.cc
+++ b/db/malloc_stats.cc
@@ -20,10 +20,6 @@ namespace rocksdb {
 
 #ifdef ROCKSDB_JEMALLOC
 
-#ifdef JEMALLOC_NO_RENAME
-#define malloc_stats_print je_malloc_stats_print
-#endif
-
 typedef struct {
   char* cur;
   char* end;
diff --git a/port/jemalloc_helper.h b/port/jemalloc_helper.h
index 0c216face..e5472ff70 100644
--- a/port/jemalloc_helper.h
+++ b/port/jemalloc_helper.h
@@ -9,6 +9,7 @@
 #ifdef __FreeBSD__
 #include <malloc_np.h>
 #else
+#define JEMALLOC_MANGLE
 #include <jemalloc/jemalloc.h>
 #endif

```

The rationale, if you're interested in upstreaming this patch, is that the current RocksDB code is broken when linking against a jemalloc that's been configured with a non-empty `--with-jemalloc-prefix` option. (In other words, I can reproduce when building using RocksDB's upstream build system, outside of cockroach, when linking against a jemalloc built with --with-jemalloc-prefix=_je.) The reason this doesn't come up in practice is because apparently nobody sets --with-jemalloc-prefix but us. We don't do it intentionally, but by default jemalloc's configure sets `--with-jemalloc-prefix=je_` on macOS. Homebrew and MacPorts both override it back to the empty string (more context: https://github.com/Homebrew/homebrew-core/issues/7488), which is why no one notices, I guess.

Anyway, it seems like it's worth working with jemallocs that have been built with `--with-jemalloc-prefix=foo`, and the patch above makes RocksDB link against jemallocs with/without prefixes. Hopefully upstream agrees. :)

**Comment by ajkr** [comment]
Understood, thanks a lot for your help! Will submit upstream.

**Comment by benesch** [comment]
Heh, thanks for doing all the heavy lifting!
